INSERT INTO samba_edvance.skills (code, description, area, level) VALUES
    ('EF01AR01', 'Experimentar diferentes formas de expressão artística.', 'Arte', 'Ensino Fundamental'),
    ('EF01AR02', 'Explorar materiais e técnicas diversas na produção artística.', 'Arte', 'Ensino Fundamental'),
    ('EF01AR03', 'Reconhecer elementos das artes visuais, música e dança.', 'Arte', 'Ensino Fundamental'),
    ('EF01AR04', 'Expressar ideias e sentimentos por meio da arte.', 'Arte', 'Ensino Fundamental'),
    ('EF01CI01', 'Identificar características dos materiais presentes no cotidiano.', 'Ciências', 'Ensino Fundamental'),
    ('EF01CI02', 'Classificar objetos de acordo com suas propriedades.', 'Ciências', 'Ensino Fundamental'),
    ('EF01CI03', 'Reconhecer usos e transformações de materiais.', 'Ciências', 'Ensino Fundamental'),
    ('EF01CI04', 'Identificar partes do corpo humano e suas funções.', 'Ciências', 'Ensino Fundamental'),
    ('EF01CI05', 'Reconhecer hábitos de higiene e cuidados com o corpo.', 'Ciências', 'Ensino Fundamental'),
    ('EF01CI06', 'Identificar características dos seres vivos.', 'Ciências', 'Ensino Fundamental'),
    ('EF01CI07', 'Reconhecer diferenças entre seres vivos e não vivos.', 'Ciências', 'Ensino Fundamental'),
    ('EF01CI08', 'Identificar relações entre os seres vivos e o ambiente.', 'Ciências', 'Ensino Fundamental'),
    ('EF01EF01', 'Participar de jogos e brincadeiras respeitando regras.', 'Educação Física', 'Ensino Fundamental'),
    ('EF01EF02', 'Experimentar movimentos corporais em diferentes contextos.', 'Educação Física', 'Ensino Fundamental'),
    ('EF01EF03', 'Reconhecer a importância da cooperação nas atividades físicas.', 'Educação Física', 'Ensino Fundamental'),
    ('EF01EF04', 'Explorar diferentes habilidades motoras básicas.', 'Educação Física', 'Ensino Fundamental'),
    ('EF01GE01', 'Descrever características do lugar onde vive.', 'Geografia', 'Ensino Fundamental'),
    ('EF01GE02', 'Identificar relações entre pessoas e o ambiente.', 'Geografia', 'Ensino Fundamental'),
    ('EF01GE03', 'Reconhecer diferentes tipos de moradia.', 'Geografia', 'Ensino Fundamental'),
    ('EF01GE04', 'Identificar elementos naturais e construídos.', 'Geografia', 'Ensino Fundamental'),
    ('EF01GE05', 'Reconhecer diferentes paisagens.', 'Geografia', 'Ensino Fundamental'),
    ('EF01GE06', 'Identificar formas de orientação no espaço.', 'Geografia', 'Ensino Fundamental'),
    ('EF01HI01', 'Identificar aspectos do seu grupo social e da sua história.', 'História', 'Ensino Fundamental'),
    ('EF01HI02', 'Reconhecer semelhanças e diferenças entre grupos sociais.', 'História', 'Ensino Fundamental'),
    ('EF01HI03', 'Identificar mudanças e permanências ao longo do tempo.', 'História', 'Ensino Fundamental'),
    ('EF01HI04', 'Reconhecer diferentes formas de organização familiar.', 'História', 'Ensino Fundamental'),
    ('EF01HI05', 'Identificar acontecimentos significativos da vida cotidiana.', 'História', 'Ensino Fundamental'),
    ('EF01LP01', 'Reconhecer que textos são lidos da esquerda para a direita e de cima para baixo.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF01LP02', 'Escrever palavras e frases estabelecendo correspondência entre sons e letras.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF01LP03', 'Identificar o tema de textos de diferentes gêneros.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF01LP04', 'Localizar informações explícitas em textos.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF01LP05', 'Reconhecer o sistema de escrita alfabética como representação dos sons da fala.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF01LP06', 'Relacionar elementos sonoros (sílabas, fonemas) às suas representações gráficas.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF01LP07', 'Identificar personagens, cenários e sequência de fatos em narrativas.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF01LP08', 'Relacionar texto verbal e não verbal.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF01LP09', 'Participar de situações de leitura compartilhada.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF01LP10', 'Produzir textos orais e escritos com apoio.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF01LP11', 'Revisar textos com apoio do professor.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF01LP12', 'Identificar diferentes gêneros textuais do cotidiano.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF01MA01', 'Utilizar números naturais como indicador de quantidade ou de ordem em diferentes situações.', 'Matemática', 'Ensino Fundamental'),
    ('EF01MA02', 'Contar de maneira exata ou aproximada, utilizando diferentes estratégias.', 'Matemática', 'Ensino Fundamental'),
    ('EF01MA03', 'Comparar e ordenar números naturais.', 'Matemática', 'Ensino Fundamental'),
    ('EF01MA04', 'Compor e decompor números naturais.', 'Matemática', 'Ensino Fundamental'),
    ('EF01MA05', 'Resolver situações-problema envolvendo adição e subtração.', 'Matemática', 'Ensino Fundamental'),
    ('EF01MA06', 'Utilizar estratégias pessoais de cálculo.', 'Matemática', 'Ensino Fundamental'),
    ('EF01MA07', 'Identificar padrões em sequências numéricas.', 'Matemática', 'Ensino Fundamental'),
    ('EF01MA08', 'Reconhecer e nomear figuras geométricas planas.', 'Matemática', 'Ensino Fundamental'),
    ('EF01MA09', 'Descrever localização e movimentação de objetos no espaço.', 'Matemática', 'Ensino Fundamental'),
    ('EF01MA10', 'Comparar grandezas como comprimento, massa e capacidade.', 'Matemática', 'Ensino Fundamental'),
    ('EF01MA11', 'Reconhecer e utilizar unidades de medida não padronizadas.', 'Matemática', 'Ensino Fundamental'),
    ('EF02AR01', 'Experimentar diferentes linguagens artísticas.', 'Arte', 'Ensino Fundamental'),
    ('EF02AR02', 'Explorar materiais e técnicas na produção artística.', 'Arte', 'Ensino Fundamental'),
    ('EF02AR03', 'Reconhecer elementos das artes visuais, música e dança.', 'Arte', 'Ensino Fundamental'),
    ('EF02AR04', 'Expressar ideias e sentimentos por meio da arte.', 'Arte', 'Ensino Fundamental'),
    ('EF02CI01', 'Identificar propriedades dos materiais e suas transformações.', 'Ciências', 'Ensino Fundamental'),
    ('EF02CI02', 'Reconhecer a importância da água e do ar para os seres vivos.', 'Ciências', 'Ensino Fundamental'),
    ('EF02CI03', 'Identificar partes das plantas e suas funções.', 'Ciências', 'Ensino Fundamental'),
    ('EF02CI04', 'Reconhecer características dos animais.', 'Ciências', 'Ensino Fundamental'),
    ('EF02CI05', 'Identificar relações entre seres vivos e ambiente.', 'Ciências', 'Ensino Fundamental'),
    ('EF02CI06', 'Reconhecer práticas de cuidado com o meio ambiente.', 'Ciências', 'Ensino Fundamental'),
    ('EF02EF01', 'Participar de jogos e brincadeiras respeitando regras.', 'Educação Física', 'Ensino Fundamental'),
    ('EF02EF02', 'Experimentar movimentos corporais em diferentes práticas.', 'Educação Física', 'Ensino Fundamental'),
    ('EF02EF03', 'Desenvolver habilidades motoras básicas.', 'Educação Física', 'Ensino Fundamental'),
    ('EF02EF04', 'Valorizar a cooperação nas atividades físicas.', 'Educação Física', 'Ensino Fundamental'),
    ('EF02GE01', 'Descrever características de diferentes lugares.', 'Geografia', 'Ensino Fundamental'),
    ('EF02GE02', 'Identificar elementos naturais e construídos nas paisagens.', 'Geografia', 'Ensino Fundamental'),
    ('EF02GE03', 'Reconhecer diferentes tipos de moradia.', 'Geografia', 'Ensino Fundamental'),
    ('EF02GE04', 'Identificar formas de orientação e localização.', 'Geografia', 'Ensino Fundamental'),
    ('EF02GE05', 'Reconhecer relações entre sociedade e natureza.', 'Geografia', 'Ensino Fundamental'),
    ('EF02GE06', 'Identificar meios de transporte e comunicação.', 'Geografia', 'Ensino Fundamental'),
    ('EF02HI01', 'Identificar diferentes formas de organização familiar e social.', 'História', 'Ensino Fundamental'),
    ('EF02HI02', 'Reconhecer mudanças e permanências ao longo do tempo.', 'História', 'Ensino Fundamental'),
    ('EF02HI03', 'Identificar registros da memória como fotos e relatos.', 'História', 'Ensino Fundamental'),
    ('EF02HI04', 'Reconhecer diferentes formas de trabalho.', 'História', 'Ensino Fundamental'),
    ('EF02HI05', 'Identificar acontecimentos do cotidiano em diferentes tempos.', 'História', 'Ensino Fundamental'),
    ('EF02LP01', 'Reconhecer o sistema de escrita alfabética como representação dos sons da fala.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF02LP02', 'Segmentar palavras em sílabas e identificar correspondência entre sons e letras.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF02LP03', 'Ler e compreender palavras e frases em textos curtos.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF02LP04', 'Localizar informações explícitas em textos.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF02LP05', 'Inferir informações em textos simples.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF02LP06', 'Identificar a finalidade de diferentes gêneros textuais.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF02LP07', 'Reconhecer elementos da narrativa como personagens e sequência de fatos.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF02LP08', 'Relacionar texto verbal e não verbal.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF02LP09', 'Produzir textos curtos com coerência.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF02LP10', 'Revisar textos com apoio.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF02LP11', 'Utilizar pontuação básica em textos escritos.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF02LP12', 'Participar de situações de leitura e escrita compartilhadas.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF02MA01', 'Utilizar números naturais até três ordens em diferentes situações.', 'Matemática', 'Ensino Fundamental'),
    ('EF02MA02', 'Compor e decompor números naturais.', 'Matemática', 'Ensino Fundamental'),
    ('EF02MA03', 'Comparar e ordenar números naturais.', 'Matemática', 'Ensino Fundamental'),
    ('EF02MA04', 'Resolver situações-problema envolvendo adição e subtração.', 'Matemática', 'Ensino Fundamental'),
    ('EF02MA05', 'Desenvolver estratégias de cálculo mental.', 'Matemática', 'Ensino Fundamental'),
    ('EF02MA06', 'Identificar padrões em sequências numéricas.', 'Matemática', 'Ensino Fundamental'),
    ('EF02MA07', 'Reconhecer figuras geométricas planas.', 'Matemática', 'Ensino Fundamental'),
    ('EF02MA08', 'Descrever localização e movimentação no espaço.', 'Matemática', 'Ensino Fundamental'),
    ('EF02MA09', 'Comparar grandezas como comprimento, massa e capacidade.', 'Matemática', 'Ensino Fundamental'),
    ('EF02MA10', 'Utilizar unidades de medida padronizadas e não padronizadas.', 'Matemática', 'Ensino Fundamental'),
    ('EF02MA11', 'Reconhecer e comparar valores monetários.', 'Matemática', 'Ensino Fundamental'),
    ('EF03AR01', 'Experimentar diferentes formas de expressão artística.', 'Arte', 'Ensino Fundamental'),
    ('EF03AR02', 'Reconhecer elementos das artes visuais.', 'Arte', 'Ensino Fundamental'),
    ('EF03AR03', 'Explorar sons e ritmos.', 'Arte', 'Ensino Fundamental'),
    ('EF03AR04', 'Participar de atividades de dança e expressão corporal.', 'Arte', 'Ensino Fundamental'),
    ('EF03CI01', 'Identificar características dos seres vivos.', 'Ciências', 'Ensino Fundamental'),
    ('EF03CI02', 'Comparar animais quanto à alimentação e habitat.', 'Ciências', 'Ensino Fundamental'),
    ('EF03CI03', 'Reconhecer partes das plantas e suas funções.', 'Ciências', 'Ensino Fundamental'),
    ('EF03CI04', 'Identificar formas de uso da água no cotidiano.', 'Ciências', 'Ensino Fundamental'),
    ('EF03CI05', 'Reconhecer a importância da preservação ambiental.', 'Ciências', 'Ensino Fundamental'),
    ('EF03CI06', 'Identificar diferentes estados físicos da matéria.', 'Ciências', 'Ensino Fundamental'),
    ('EF03CI07', 'Reconhecer fontes de energia no cotidiano.', 'Ciências', 'Ensino Fundamental'),
    ('EF03GE01', 'Identificar características do lugar onde vive.', 'Geografia', 'Ensino Fundamental'),
    ('EF03GE02', 'Reconhecer diferentes paisagens naturais e modificadas.', 'Geografia', 'Ensino Fundamental'),
    ('EF03GE03', 'Identificar formas de representação do espaço (mapas simples).', 'Geografia', 'Ensino Fundamental'),
    ('EF03GE04', 'Reconhecer atividades econômicas locais.', 'Geografia', 'Ensino Fundamental'),
    ('EF03GE05', 'Identificar elementos naturais e culturais do espaço.', 'Geografia', 'Ensino Fundamental'),
    ('EF03HI01', 'Identificar mudanças e permanências ao longo do tempo.', 'História', 'Ensino Fundamental'),
    ('EF03HI02', 'Reconhecer diferentes grupos sociais na comunidade.', 'História', 'Ensino Fundamental'),
    ('EF03HI03', 'Identificar tradições culturais locais.', 'História', 'Ensino Fundamental'),
    ('EF03HI04', 'Compreender noções de passado, presente e futuro.', 'História', 'Ensino Fundamental'),
    ('EF03HI05', 'Valorizar a diversidade cultural.', 'História', 'Ensino Fundamental'),
    ('EF03LP01', 'Ler e escrever palavras com correspondências regulares entre grafemas e fonemas.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF03LP02', 'Ler e escrever palavras com correspondências irregulares mais frequentes na língua.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF03LP03', 'Ler e compreender textos de diferentes gêneros, com autonomia.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF03LP04', 'Inferir informações implícitas em textos.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF03LP05', 'Identificar a ideia central de textos.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF03LP06', 'Reconhecer a função social de diferentes gêneros textuais.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF03LP07', 'Planejar e produzir textos de diferentes gêneros, considerando a situação comunicativa.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF03LP08', 'Revisar textos com apoio do professor e colegas.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF03LP09', 'Utilizar pontuação básica (ponto final, interrogação e exclamação).', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF03LP10', 'Reconhecer e utilizar letras maiúsculas e minúsculas corretamente.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF03LP11', 'Identificar elementos narrativos (personagens, tempo, espaço).', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF03LP12', 'Recontar histórias ouvidas ou lidas, mantendo a sequência lógica.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF03MA01', 'Ler, escrever e comparar números naturais até a ordem de milhar.', 'Matemática', 'Ensino Fundamental'),
    ('EF03MA02', 'Compor e decompor números naturais.', 'Matemática', 'Ensino Fundamental'),
    ('EF03MA03', 'Resolver e elaborar problemas de adição e subtração.', 'Matemática', 'Ensino Fundamental'),
    ('EF03MA04', 'Resolver problemas de multiplicação.', 'Matemática', 'Ensino Fundamental'),
    ('EF03MA05', 'Resolver problemas de divisão simples.', 'Matemática', 'Ensino Fundamental'),
    ('EF03MA06', 'Identificar regularidades em sequências numéricas.', 'Matemática', 'Ensino Fundamental'),
    ('EF03MA07', 'Reconhecer e comparar figuras geométricas planas.', 'Matemática', 'Ensino Fundamental'),
    ('EF03MA08', 'Identificar simetria em figuras.', 'Matemática', 'Ensino Fundamental'),
    ('EF03MA09', 'Medir comprimentos utilizando unidades padronizadas e não padronizadas.', 'Matemática', 'Ensino Fundamental'),
    ('EF03MA10', 'Resolver problemas envolvendo medidas de tempo.', 'Matemática', 'Ensino Fundamental'),
    ('EF03MA11', 'Coletar e organizar dados em tabelas e gráficos simples.', 'Matemática', 'Ensino Fundamental'),
    ('EF03MA12', 'Interpretar dados apresentados em gráficos e tabelas.', 'Matemática', 'Ensino Fundamental'),
    ('EF04AR01', 'Experimentar diferentes linguagens artísticas.', 'Arte', 'Ensino Fundamental'),
    ('EF04AR02', 'Reconhecer elementos das artes visuais.', 'Arte', 'Ensino Fundamental'),
    ('EF04AR03', 'Explorar ritmos e sons.', 'Arte', 'Ensino Fundamental'),
    ('EF04AR04', 'Expressar-se por meio da dança e do corpo.', 'Arte', 'Ensino Fundamental'),
    ('EF04CI01', 'Identificar características dos ecossistemas.', 'Ciências', 'Ensino Fundamental'),
    ('EF04CI02', 'Reconhecer relações entre seres vivos.', 'Ciências', 'Ensino Fundamental'),
    ('EF04CI03', 'Identificar cadeias alimentares simples.', 'Ciências', 'Ensino Fundamental'),
    ('EF04CI04', 'Compreender o ciclo da água.', 'Ciências', 'Ensino Fundamental'),
    ('EF04CI05', 'Identificar formas de poluição ambiental.', 'Ciências', 'Ensino Fundamental'),
    ('EF04CI06', 'Reconhecer a importância da preservação ambiental.', 'Ciências', 'Ensino Fundamental'),
    ('EF04CI07', 'Identificar transformações da matéria.', 'Ciências', 'Ensino Fundamental'),
    ('EF04EF01', 'Participar de jogos e brincadeiras.', 'Educação Física', 'Ensino Fundamental'),
    ('EF04EF02', 'Desenvolver habilidades motoras.', 'Educação Física', 'Ensino Fundamental'),
    ('EF04EF03', 'Respeitar regras e colegas.', 'Educação Física', 'Ensino Fundamental'),
    ('EF04EF04', 'Valorizar o trabalho em equipe.', 'Educação Física', 'Ensino Fundamental'),
    ('EF04GE01', 'Identificar características do espaço geográfico.', 'Geografia', 'Ensino Fundamental'),
    ('EF04GE02', 'Reconhecer paisagens naturais e modificadas.', 'Geografia', 'Ensino Fundamental'),
    ('EF04GE03', 'Interpretar mapas simples.', 'Geografia', 'Ensino Fundamental'),
    ('EF04GE04', 'Identificar atividades econômicas.', 'Geografia', 'Ensino Fundamental'),
    ('EF04GE05', 'Reconhecer impactos ambientais das ações humanas.', 'Geografia', 'Ensino Fundamental'),
    ('EF04HI01', 'Reconhecer diferentes formas de organização social.', 'História', 'Ensino Fundamental'),
    ('EF04HI02', 'Identificar mudanças e permanências ao longo do tempo.', 'História', 'Ensino Fundamental'),
    ('EF04HI03', 'Reconhecer a importância da cultura e tradições.', 'História', 'Ensino Fundamental'),
    ('EF04HI04', 'Identificar fatos históricos locais e regionais.', 'História', 'Ensino Fundamental'),
    ('EF04HI05', 'Valorizar a diversidade cultural.', 'História', 'Ensino Fundamental'),
    ('EF04LP01', 'Ler e compreender textos de diferentes gêneros com maior autonomia.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF04LP02', 'Localizar informações explícitas em textos.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF04LP03', 'Inferir informações implícitas em textos.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF04LP04', 'Identificar a ideia central de textos.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF04LP05', 'Reconhecer a finalidade de diferentes gêneros textuais.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF04LP06', 'Planejar e produzir textos considerando a situação comunicativa.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF04LP07', 'Revisar textos quanto à ortografia e pontuação.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF04LP08', 'Utilizar pontuação em diálogos (travessão).', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF04LP09', 'Empregar corretamente letras maiúsculas e minúsculas.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF04LP10', 'Identificar elementos narrativos (enredo, personagens, tempo e espaço).', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF04LP11', 'Recontar e resumir textos lidos.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF04LP12', 'Reconhecer diferentes tipos de discurso (direto e indireto).', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF04MA01', 'Ler, escrever e comparar números naturais até a ordem de dezena de milhar.', 'Matemática', 'Ensino Fundamental'),
    ('EF04MA02', 'Compor e decompor números naturais.', 'Matemática', 'Ensino Fundamental'),
    ('EF04MA03', 'Resolver e elaborar problemas de adição e subtração.', 'Matemática', 'Ensino Fundamental'),
    ('EF04MA04', 'Resolver problemas de multiplicação.', 'Matemática', 'Ensino Fundamental'),
    ('EF04MA05', 'Resolver problemas de divisão.', 'Matemática', 'Ensino Fundamental'),
    ('EF04MA06', 'Identificar e completar sequências numéricas.', 'Matemática', 'Ensino Fundamental'),
    ('EF04MA07', 'Reconhecer frações simples.', 'Matemática', 'Ensino Fundamental'),
    ('EF04MA08', 'Comparar frações com mesmo denominador.', 'Matemática', 'Ensino Fundamental'),
    ('EF04MA09', 'Identificar figuras geométricas planas.', 'Matemática', 'Ensino Fundamental'),
    ('EF04MA10', 'Calcular perímetro de figuras.', 'Matemática', 'Ensino Fundamental'),
    ('EF04MA11', 'Medir grandezas (comprimento, massa e capacidade).', 'Matemática', 'Ensino Fundamental'),
    ('EF04MA12', 'Interpretar e construir gráficos e tabelas.', 'Matemática', 'Ensino Fundamental'),
    ('EF05AR01', 'Experimentar diferentes linguagens artísticas.', 'Arte', 'Ensino Fundamental'),
    ('EF05AR02', 'Reconhecer elementos das artes visuais e musicais.', 'Arte', 'Ensino Fundamental'),
    ('EF05AR03', 'Explorar diferentes formas de expressão artística.', 'Arte', 'Ensino Fundamental'),
    ('EF05AR04', 'Valorizar produções artísticas diversas.', 'Arte', 'Ensino Fundamental'),
    ('EF05CI01', 'Compreender a organização dos ecossistemas.', 'Ciências', 'Ensino Fundamental'),
    ('EF05CI02', 'Identificar cadeias e teias alimentares.', 'Ciências', 'Ensino Fundamental'),
    ('EF05CI03', 'Reconhecer a importância da água e seu ciclo.', 'Ciências', 'Ensino Fundamental'),
    ('EF05CI04', 'Identificar fontes e tipos de energia.', 'Ciências', 'Ensino Fundamental'),
    ('EF05CI05', 'Compreender transformações da matéria.', 'Ciências', 'Ensino Fundamental'),
    ('EF05CI06', 'Reconhecer impactos ambientais causados pelo ser humano.', 'Ciências', 'Ensino Fundamental'),
    ('EF05CI07', 'Propor ações de preservação ambiental.', 'Ciências', 'Ensino Fundamental'),
    ('EF05GE01', 'Identificar características do território brasileiro.', 'Geografia', 'Ensino Fundamental'),
    ('EF05GE02', 'Reconhecer diferentes paisagens do Brasil.', 'Geografia', 'Ensino Fundamental'),
    ('EF05GE03', 'Interpretar mapas e representações cartográficas.', 'Geografia', 'Ensino Fundamental'),
    ('EF05GE04', 'Identificar atividades econômicas no Brasil.', 'Geografia', 'Ensino Fundamental'),
    ('EF05GE05', 'Compreender impactos ambientais no território.', 'Geografia', 'Ensino Fundamental'),
    ('EF05HI01', 'Reconhecer processos históricos locais e regionais.', 'História', 'Ensino Fundamental'),
    ('EF05HI02', 'Identificar mudanças e permanências ao longo do tempo.', 'História', 'Ensino Fundamental'),
    ('EF05HI03', 'Compreender a formação da sociedade brasileira.', 'História', 'Ensino Fundamental'),
    ('EF05HI04', 'Reconhecer a diversidade cultural.', 'História', 'Ensino Fundamental'),
    ('EF05HI05', 'Valorizar patrimônios históricos e culturais.', 'História', 'Ensino Fundamental'),
    ('EF05LP01', 'Ler e compreender textos de diferentes gêneros com autonomia.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF05LP02', 'Localizar e comparar informações em textos.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF05LP03', 'Inferir informações implícitas em textos.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF05LP04', 'Identificar a ideia central e os temas de textos.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF05LP05', 'Reconhecer a finalidade de diferentes gêneros textuais.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF05LP06', 'Planejar e produzir textos considerando o contexto comunicativo.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF05LP07', 'Revisar textos quanto à ortografia, pontuação e coerência.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF05LP08', 'Utilizar corretamente pontuação em diálogos e narrativas.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF05LP09', 'Empregar normas ortográficas da língua portuguesa.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF05LP10', 'Identificar e analisar elementos narrativos.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF05LP11', 'Resumir e recontar textos mantendo coerência.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF05LP12', 'Reconhecer diferentes vozes no texto (narrador e personagens).', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF05MA01', 'Ler, escrever e comparar números naturais até a ordem de centena de milhar.', 'Matemática', 'Ensino Fundamental'),
    ('EF05MA02', 'Compor e decompor números naturais.', 'Matemática', 'Ensino Fundamental'),
    ('EF05MA03', 'Resolver e elaborar problemas de adição e subtração.', 'Matemática', 'Ensino Fundamental'),
    ('EF05MA04', 'Resolver problemas de multiplicação e divisão.', 'Matemática', 'Ensino Fundamental'),
    ('EF05MA05', 'Reconhecer e comparar frações.', 'Matemática', 'Ensino Fundamental'),
    ('EF05MA06', 'Relacionar frações e números decimais.', 'Matemática', 'Ensino Fundamental'),
    ('EF05MA07', 'Resolver problemas com números decimais.', 'Matemática', 'Ensino Fundamental'),
    ('EF05MA08', 'Identificar figuras geométricas planas e espaciais.', 'Matemática', 'Ensino Fundamental'),
    ('EF05MA09', 'Calcular perímetro e área de figuras simples.', 'Matemática', 'Ensino Fundamental'),
    ('EF05MA10', 'Medir grandezas e resolver problemas envolvendo medidas.', 'Matemática', 'Ensino Fundamental'),
    ('EF05MA11', 'Interpretar e construir gráficos e tabelas.', 'Matemática', 'Ensino Fundamental'),
    ('EF05MA12', 'Resolver problemas envolvendo dados e informações.', 'Matemática', 'Ensino Fundamental'),
    ('EF06AR01', 'Experimentar diferentes linguagens artísticas.', 'Arte', 'Ensino Fundamental'),
    ('EF06AR02', 'Analisar elementos das artes visuais.', 'Arte', 'Ensino Fundamental'),
    ('EF06AR03', 'Explorar sons e ritmos.', 'Arte', 'Ensino Fundamental'),
    ('EF06CI01', 'Identificar níveis de organização dos seres vivos.', 'Ciências', 'Ensino Fundamental'),
    ('EF06CI02', 'Compreender a célula como unidade da vida.', 'Ciências', 'Ensino Fundamental'),
    ('EF06CI03', 'Reconhecer características dos seres vivos.', 'Ciências', 'Ensino Fundamental'),
    ('EF06CI04', 'Identificar relações ecológicas.', 'Ciências', 'Ensino Fundamental'),
    ('EF06CI05', 'Compreender cadeias alimentares.', 'Ciências', 'Ensino Fundamental'),
    ('EF06CI06', 'Identificar componentes do sistema solar.', 'Ciências', 'Ensino Fundamental'),
    ('EF06CI07', 'Reconhecer movimentos da Terra.', 'Ciências', 'Ensino Fundamental'),
    ('EF06CI08', 'Compreender fenômenos naturais.', 'Ciências', 'Ensino Fundamental'),
    ('EF06GE01', 'Identificar elementos do espaço geográfico.', 'Geografia', 'Ensino Fundamental'),
    ('EF06GE02', 'Reconhecer diferentes paisagens.', 'Geografia', 'Ensino Fundamental'),
    ('EF06GE03', 'Interpretar mapas e representações cartográficas.', 'Geografia', 'Ensino Fundamental'),
    ('EF06GE04', 'Compreender a relação sociedade-natureza.', 'Geografia', 'Ensino Fundamental'),
    ('EF06GE05', 'Identificar atividades econômicas.', 'Geografia', 'Ensino Fundamental'),
    ('EF06HI01', 'Compreender a noção de tempo histórico.', 'História', 'Ensino Fundamental'),
    ('EF06HI02', 'Identificar fontes históricas.', 'História', 'Ensino Fundamental'),
    ('EF06HI03', 'Reconhecer a importância das civilizações antigas.', 'História', 'Ensino Fundamental'),
    ('EF06HI04', 'Comparar diferentes sociedades antigas.', 'História', 'Ensino Fundamental'),
    ('EF06HI05', 'Identificar aspectos culturais e sociais das civilizações.', 'História', 'Ensino Fundamental'),
    ('EF06LP01', 'Identificar o tema e a ideia central em textos de diferentes gêneros.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF06LP02', 'Localizar informações explícitas em textos.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF06LP03', 'Inferir informações implícitas em textos.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF06LP04', 'Reconhecer a finalidade de textos de diferentes gêneros.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF06LP05', 'Analisar elementos da narrativa (personagens, tempo, espaço, enredo).', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF06LP06', 'Comparar diferentes textos sobre o mesmo tema.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF06LP07', 'Planejar e produzir textos considerando o contexto comunicativo.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF06LP08', 'Revisar textos quanto à coerência, coesão e adequação linguística.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF06LP09', 'Utilizar corretamente pontuação e ortografia.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF06LP10', 'Reconhecer efeitos de sentido produzidos por recursos linguísticos.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF06LP11', 'Identificar diferentes vozes no texto.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF06LP12', 'Participar de práticas de leitura e produção oral.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF06MA01', 'Resolver e elaborar problemas com números naturais.', 'Matemática', 'Ensino Fundamental'),
    ('EF06MA02', 'Compreender e utilizar operações com números naturais.', 'Matemática', 'Ensino Fundamental'),
    ('EF06MA03', 'Resolver problemas envolvendo múltiplos e divisores.', 'Matemática', 'Ensino Fundamental'),
    ('EF06MA04', 'Compreender frações e suas representações.', 'Matemática', 'Ensino Fundamental'),
    ('EF06MA05', 'Resolver problemas com números racionais.', 'Matemática', 'Ensino Fundamental'),
    ('EF06MA06', 'Identificar e representar números em diferentes formas.', 'Matemática', 'Ensino Fundamental'),
    ('EF06MA07', 'Reconhecer e classificar figuras geométricas.', 'Matemática', 'Ensino Fundamental'),
    ('EF06MA08', 'Calcular perímetro e área de figuras planas.', 'Matemática', 'Ensino Fundamental'),
    ('EF06MA09', 'Resolver problemas envolvendo medidas.', 'Matemática', 'Ensino Fundamental'),
    ('EF06MA10', 'Interpretar e construir gráficos e tabelas.', 'Matemática', 'Ensino Fundamental'),
    ('EF06MA11', 'Identificar padrões e regularidades.', 'Matemática', 'Ensino Fundamental'),
    ('EF06MA12', 'Resolver problemas envolvendo proporcionalidade simples.', 'Matemática', 'Ensino Fundamental'),
    ('EF07AR01', 'Experimentar diferentes linguagens artísticas.', 'Arte', 'Ensino Fundamental'),
    ('EF07AR02', 'Analisar elementos das artes visuais.', 'Arte', 'Ensino Fundamental'),
    ('EF07AR03', 'Explorar sons, ritmos e composições.', 'Arte', 'Ensino Fundamental'),
    ('EF07AR04', 'Expressar-se corporalmente.', 'Arte', 'Ensino Fundamental'),
    ('EF07CI01', 'Compreender a organização dos seres vivos.', 'Ciências', 'Ensino Fundamental'),
    ('EF07CI02', 'Identificar características dos ecossistemas.', 'Ciências', 'Ensino Fundamental'),
    ('EF07CI03', 'Analisar cadeias e teias alimentares.', 'Ciências', 'Ensino Fundamental'),
    ('EF07CI04', 'Compreender a dinâmica da Terra.', 'Ciências', 'Ensino Fundamental'),
    ('EF07CI05', 'Identificar fenômenos naturais.', 'Ciências', 'Ensino Fundamental'),
    ('EF07CI06', 'Reconhecer transformações da matéria.', 'Ciências', 'Ensino Fundamental'),
    ('EF07CI07', 'Compreender fontes e tipos de energia.', 'Ciências', 'Ensino Fundamental'),
    ('EF07GE01', 'Identificar elementos do espaço geográfico.', 'Geografia', 'Ensino Fundamental'),
    ('EF07GE02', 'Analisar paisagens naturais e modificadas.', 'Geografia', 'Ensino Fundamental'),
    ('EF07GE03', 'Interpretar mapas e gráficos.', 'Geografia', 'Ensino Fundamental'),
    ('EF07GE04', 'Compreender a relação sociedade-natureza.', 'Geografia', 'Ensino Fundamental'),
    ('EF07GE05', 'Identificar atividades econômicas.', 'Geografia', 'Ensino Fundamental'),
    ('EF07HI01', 'Compreender processos históricos e sociais.', 'História', 'Ensino Fundamental'),
    ('EF07HI02', 'Identificar transformações ao longo do tempo.', 'História', 'Ensino Fundamental'),
    ('EF07HI03', 'Reconhecer a formação de sociedades.', 'História', 'Ensino Fundamental'),
    ('EF07HI04', 'Analisar diferentes culturas.', 'História', 'Ensino Fundamental'),
    ('EF07HI05', 'Valorizar a diversidade cultural.', 'História', 'Ensino Fundamental'),
    ('EF07LP01', 'Identificar tema e tese em textos de diferentes gêneros.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF07LP02', 'Localizar e comparar informações em textos.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF07LP03', 'Inferir informações implícitas em textos.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF07LP04', 'Analisar a finalidade e o público-alvo de textos.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF07LP05', 'Analisar elementos da narrativa e seus efeitos de sentido.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF07LP06', 'Comparar diferentes pontos de vista em textos.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF07LP07', 'Planejar e produzir textos argumentativos e narrativos.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF07LP08', 'Revisar textos quanto à coerência, coesão e adequação.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF07LP09', 'Utilizar recursos linguísticos e gramaticais adequados.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF07LP10', 'Reconhecer efeitos de sentido em figuras de linguagem.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF07LP11', 'Identificar vozes e discursos em textos.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF07LP12', 'Participar de práticas de leitura, escrita e oralidade.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF07MA01', 'Resolver e elaborar problemas com números inteiros.', 'Matemática', 'Ensino Fundamental'),
    ('EF07MA02', 'Compreender operações com números inteiros.', 'Matemática', 'Ensino Fundamental'),
    ('EF07MA03', 'Resolver problemas com números racionais.', 'Matemática', 'Ensino Fundamental'),
    ('EF07MA04', 'Compreender porcentagens e suas aplicações.', 'Matemática', 'Ensino Fundamental'),
    ('EF07MA05', 'Resolver problemas envolvendo razão e proporção.', 'Matemática', 'Ensino Fundamental'),
    ('EF07MA06', 'Identificar expressões algébricas.', 'Matemática', 'Ensino Fundamental'),
    ('EF07MA07', 'Resolver equações do 1º grau.', 'Matemática', 'Ensino Fundamental'),
    ('EF07MA08', 'Reconhecer e representar figuras geométricas.', 'Matemática', 'Ensino Fundamental'),
    ('EF07MA09', 'Calcular área e perímetro de figuras planas.', 'Matemática', 'Ensino Fundamental'),
    ('EF07MA10', 'Resolver problemas envolvendo medidas.', 'Matemática', 'Ensino Fundamental'),
    ('EF07MA11', 'Interpretar e construir gráficos e tabelas.', 'Matemática', 'Ensino Fundamental'),
    ('EF07MA12', 'Identificar padrões e regularidades.', 'Matemática', 'Ensino Fundamental'),
    ('EF08AR01', 'Experimentar diferentes linguagens artísticas.', 'Arte', 'Ensino Fundamental'),
    ('EF08AR02', 'Analisar elementos das artes visuais.', 'Arte', 'Ensino Fundamental'),
    ('EF08AR03', 'Explorar sons, ritmos e composições.', 'Arte', 'Ensino Fundamental'),
    ('EF08AR04', 'Expressar-se corporalmente.', 'Arte', 'Ensino Fundamental'),
    ('EF08CI01', 'Compreender a organização dos seres vivos.', 'Ciências', 'Ensino Fundamental'),
    ('EF08CI02', 'Analisar relações ecológicas.', 'Ciências', 'Ensino Fundamental'),
    ('EF08CI03', 'Compreender cadeias e teias alimentares.', 'Ciências', 'Ensino Fundamental'),
    ('EF08CI04', 'Identificar transformações químicas e físicas.', 'Ciências', 'Ensino Fundamental'),
    ('EF08CI05', 'Compreender fontes e formas de energia.', 'Ciências', 'Ensino Fundamental'),
    ('EF08CI06', 'Analisar impactos ambientais.', 'Ciências', 'Ensino Fundamental'),
    ('EF08CI07', 'Compreender fenômenos naturais.', 'Ciências', 'Ensino Fundamental'),
    ('EF08GE01', 'Analisar elementos do espaço geográfico.', 'Geografia', 'Ensino Fundamental'),
    ('EF08GE02', 'Compreender dinâmicas ambientais.', 'Geografia', 'Ensino Fundamental'),
    ('EF08GE03', 'Interpretar mapas, gráficos e tabelas.', 'Geografia', 'Ensino Fundamental'),
    ('EF08GE04', 'Analisar a relação sociedade-natureza.', 'Geografia', 'Ensino Fundamental'),
    ('EF08GE05', 'Identificar atividades econômicas.', 'Geografia', 'Ensino Fundamental'),
    ('EF08HI01', 'Analisar processos históricos.', 'História', 'Ensino Fundamental'),
    ('EF08HI02', 'Identificar transformações sociais e culturais.', 'História', 'Ensino Fundamental'),
    ('EF08HI03', 'Compreender a formação de sociedades modernas.', 'História', 'Ensino Fundamental'),
    ('EF08HI04', 'Analisar diferentes culturas.', 'História', 'Ensino Fundamental'),
    ('EF08HI05', 'Valorizar a diversidade cultural.', 'História', 'Ensino Fundamental'),
    ('EF08LP01', 'Identificar e analisar tema, tese e argumentos em textos.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF08LP02', 'Localizar e comparar informações em textos de diferentes fontes.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF08LP03', 'Inferir informações implícitas e pressupostos em textos.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF08LP04', 'Analisar a finalidade e o público-alvo de textos.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF08LP05', 'Avaliar a consistência de argumentos em textos.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF08LP06', 'Comparar diferentes pontos de vista sobre um tema.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF08LP07', 'Planejar e produzir textos argumentativos.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF08LP08', 'Revisar textos quanto à coerência, coesão e adequação linguística.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF08LP09', 'Utilizar recursos linguísticos e gramaticais de forma adequada.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF08LP10', 'Analisar efeitos de sentido em figuras de linguagem.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF08LP11', 'Identificar vozes e discursos em textos.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF08LP12', 'Participar de práticas de leitura, escrita e oralidade.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF08MA01', 'Resolver e elaborar problemas com números racionais.', 'Matemática', 'Ensino Fundamental'),
    ('EF08MA02', 'Compreender operações com números racionais.', 'Matemática', 'Ensino Fundamental'),
    ('EF08MA03', 'Resolver problemas envolvendo porcentagens.', 'Matemática', 'Ensino Fundamental'),
    ('EF08MA04', 'Resolver problemas envolvendo razão e proporção.', 'Matemática', 'Ensino Fundamental'),
    ('EF08MA05', 'Compreender expressões algébricas.', 'Matemática', 'Ensino Fundamental'),
    ('EF08MA06', 'Resolver equações do 1º grau.', 'Matemática', 'Ensino Fundamental'),
    ('EF08MA07', 'Resolver sistemas de equações simples.', 'Matemática', 'Ensino Fundamental'),
    ('EF08MA08', 'Reconhecer e representar figuras geométricas.', 'Matemática', 'Ensino Fundamental'),
    ('EF08MA09', 'Calcular área e perímetro de figuras planas.', 'Matemática', 'Ensino Fundamental'),
    ('EF08MA10', 'Resolver problemas envolvendo medidas.', 'Matemática', 'Ensino Fundamental'),
    ('EF08MA11', 'Interpretar e construir gráficos e tabelas.', 'Matemática', 'Ensino Fundamental'),
    ('EF08MA12', 'Identificar padrões e regularidades.', 'Matemática', 'Ensino Fundamental'),
    ('EF09AR01', 'Experimentar diferentes linguagens artísticas.', 'Arte', 'Ensino Fundamental'),
    ('EF09AR02', 'Analisar elementos das artes visuais.', 'Arte', 'Ensino Fundamental'),
    ('EF09AR03', 'Explorar sons, ritmos e composições.', 'Arte', 'Ensino Fundamental'),
    ('EF09AR04', 'Expressar-se corporalmente.', 'Arte', 'Ensino Fundamental'),
    ('EF09CI01', 'Compreender a organização dos seres vivos.', 'Ciências', 'Ensino Fundamental'),
    ('EF09CI02', 'Analisar relações ecológicas.', 'Ciências', 'Ensino Fundamental'),
    ('EF09CI03', 'Compreender cadeias e teias alimentares.', 'Ciências', 'Ensino Fundamental'),
    ('EF09CI04', 'Identificar transformações químicas e físicas.', 'Ciências', 'Ensino Fundamental'),
    ('EF09CI05', 'Compreender fontes e formas de energia.', 'Ciências', 'Ensino Fundamental'),
    ('EF09CI06', 'Analisar impactos ambientais.', 'Ciências', 'Ensino Fundamental'),
    ('EF09CI07', 'Compreender fenômenos naturais.', 'Ciências', 'Ensino Fundamental'),
    ('EF09GE01', 'Analisar elementos do espaço geográfico.', 'Geografia', 'Ensino Fundamental'),
    ('EF09GE02', 'Compreender dinâmicas ambientais.', 'Geografia', 'Ensino Fundamental'),
    ('EF09GE03', 'Interpretar mapas, gráficos e tabelas.', 'Geografia', 'Ensino Fundamental'),
    ('EF09GE04', 'Analisar a relação sociedade-natureza.', 'Geografia', 'Ensino Fundamental'),
    ('EF09GE05', 'Identificar atividades econômicas.', 'Geografia', 'Ensino Fundamental'),
    ('EF09HI01', 'Analisar processos históricos.', 'História', 'Ensino Fundamental'),
    ('EF09HI02', 'Compreender transformações sociais e culturais.', 'História', 'Ensino Fundamental'),
    ('EF09HI03', 'Analisar a formação do mundo contemporâneo.', 'História', 'Ensino Fundamental'),
    ('EF09HI04', 'Comparar diferentes culturas.', 'História', 'Ensino Fundamental'),
    ('EF09HI05', 'Valorizar a diversidade cultural.', 'História', 'Ensino Fundamental'),
    ('EF09LP01', 'Analisar tema, tese e argumentos em textos de diferentes gêneros.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF09LP02', 'Comparar informações e pontos de vista em diferentes textos.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF09LP03', 'Inferir informações implícitas e avaliar pressupostos.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF09LP04', 'Analisar a finalidade e o público-alvo de textos.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF09LP05', 'Avaliar a consistência e a validade de argumentos.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF09LP06', 'Analisar estratégias argumentativas.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF09LP07', 'Produzir textos argumentativos com coerência e coesão.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF09LP08', 'Revisar textos quanto à adequação linguística.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF09LP09', 'Utilizar recursos linguísticos e gramaticais adequados.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF09LP10', 'Analisar efeitos de sentido em figuras de linguagem.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF09LP11', 'Identificar vozes e discursos em textos.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF09LP12', 'Participar de práticas de leitura, escrita e oralidade.', 'Língua Portuguesa', 'Ensino Fundamental'),
    ('EF09MA01', 'Resolver e elaborar problemas com números reais.', 'Matemática', 'Ensino Fundamental'),
    ('EF09MA02', 'Compreender operações com números reais.', 'Matemática', 'Ensino Fundamental'),
    ('EF09MA03', 'Resolver problemas envolvendo porcentagens e juros simples.', 'Matemática', 'Ensino Fundamental'),
    ('EF09MA04', 'Compreender expressões algébricas.', 'Matemática', 'Ensino Fundamental'),
    ('EF09MA05', 'Resolver equações do 1º grau.', 'Matemática', 'Ensino Fundamental'),
    ('EF09MA06', 'Resolver sistemas de equações.', 'Matemática', 'Ensino Fundamental'),
    ('EF09MA07', 'Compreender funções.', 'Matemática', 'Ensino Fundamental'),
    ('EF09MA08', 'Reconhecer e representar figuras geométricas.', 'Matemática', 'Ensino Fundamental'),
    ('EF09MA09', 'Calcular área e perímetro de figuras planas.', 'Matemática', 'Ensino Fundamental'),
    ('EF09MA10', 'Resolver problemas envolvendo medidas.', 'Matemática', 'Ensino Fundamental'),
    ('EF09MA11', 'Interpretar e construir gráficos e tabelas.', 'Matemática', 'Ensino Fundamental'),
    ('EF09MA12', 'Identificar padrões e regularidades.', 'Matemática', 'Ensino Fundamental'),
    ('EM13CHS101', 'Analisar processos históricos e sociais.', 'Ciências Humanas e Sociais', 'Ensino Médio'),
    ('EM13CHS102', 'Compreender transformações no espaço geográfico.', 'Ciências Humanas e Sociais', 'Ensino Médio'),
    ('EM13CHS103', 'Interpretar relações de poder e organização social.', 'Ciências Humanas e Sociais', 'Ensino Médio'),
    ('EM13CHS104', 'Analisar diferentes culturas.', 'Ciências Humanas e Sociais', 'Ensino Médio'),
    ('EM13CHS105', 'Compreender cidadania e direitos humanos.', 'Ciências Humanas e Sociais', 'Ensino Médio'),
    ('EM13CHS106', 'Relacionar sociedade,  economia e política.', 'Ciências Humanas e Sociais', 'Ensino Médio'),
    ('EM13CHS201', 'Analisar processos históricos e sociais.', 'Ciências Humanas e Sociais', 'Ensino Médio'),
    ('EM13CHS202', 'Compreender dinâmicas do espaço geográfico.', 'Ciências Humanas e Sociais', 'Ensino Médio'),
    ('EM13CHS203', 'Interpretar relações de poder.', 'Ciências Humanas e Sociais', 'Ensino Médio'),
    ('EM13CHS301', 'Analisar processos históricos contemporâneos.', 'Ciências Humanas e Sociais', 'Ensino Médio'),
    ('EM13CHS302', 'Compreender dinâmicas geopolíticas.', 'Ciências Humanas e Sociais', 'Ensino Médio'),
    ('EM13CHS303', 'Avaliar relações de poder e conflitos sociais.', 'Ciências Humanas e Sociais', 'Ensino Médio'),
    ('EM13CNT101', 'Compreender fenômenos naturais com base em conceitos científicos.', 'Ciências da Natureza', 'Ensino Médio'),
    ('EM13CNT102', 'Analisar transformações da matéria e energia.', 'Ciências da Natureza', 'Ensino Médio'),
    ('EM13CNT103', 'Relacionar ciência,  tecnologia e sociedade.', 'Ciências da Natureza', 'Ensino Médio'),
    ('EM13CNT104', 'Interpretar fenômenos físicos e químicos.', 'Ciências da Natureza', 'Ensino Médio'),
    ('EM13CNT105', 'Compreender processos biológicos.', 'Ciências da Natureza', 'Ensino Médio'),
    ('EM13CNT106', 'Analisar impactos ambientais.', 'Ciências da Natureza', 'Ensino Médio'),
    ('EM13CNT201', 'Analisar fenômenos naturais com base científica.', 'Ciências da Natureza', 'Ensino Médio'),
    ('EM13CNT202', 'Compreender transformações químicas e físicas.', 'Ciências da Natureza', 'Ensino Médio'),
    ('EM13CNT203', 'Relacionar ciência,  tecnologia e sociedade.', 'Ciências da Natureza', 'Ensino Médio'),
    ('EM13CNT204', 'Interpretar fenômenos físicos.', 'Ciências da Natureza', 'Ensino Médio'),
    ('EM13CNT205', 'Compreender processos biológicos.', 'Ciências da Natureza', 'Ensino Médio'),
    ('EM13CNT206', 'Avaliar impactos ambientais.', 'Ciências da Natureza', 'Ensino Médio'),
    ('EM13CNT301', 'Analisar fenômenos naturais com base em modelos científicos.', 'Ciências da Natureza', 'Ensino Médio'),
    ('EM13CNT302', 'Compreender transformações químicas,  físicas e biológicas.', 'Ciências da Natureza', 'Ensino Médio'),
    ('EM13CNT303', 'Avaliar relações entre ciência,  tecnologia e sociedade.', 'Ciências da Natureza', 'Ensino Médio'),
    ('EM13CNT304', 'Interpretar fenômenos físicos e suas aplicações.', 'Ciências da Natureza', 'Ensino Médio'),
    ('EM13CNT305', 'Compreender processos biológicos complexos.', 'Ciências da Natureza', 'Ensino Médio'),
    ('EM13CNT306', 'Avaliar impactos ambientais e propor soluções.', 'Ciências da Natureza', 'Ensino Médio'),
    ('EM13LGG101', 'Analisar diferentes linguagens e suas funções em contextos sociais.', 'Linguagens', 'Ensino Médio'),
    ('EM13LGG102', 'Compreender processos de produção e circulação de textos.', 'Linguagens', 'Ensino Médio'),
    ('EM13LGG103', 'Analisar discursos e seus efeitos de sentido.', 'Linguagens', 'Ensino Médio'),
    ('EM13LGG104', 'Utilizar diferentes linguagens para se expressar.', 'Linguagens', 'Ensino Médio'),
    ('EM13LGG105', 'Interpretar textos multimodais.', 'Linguagens', 'Ensino Médio'),
    ('EM13LGG106', 'Produzir textos em diferentes gêneros e mídias.', 'Linguagens', 'Ensino Médio'),
    ('EM13LGG201', 'Analisar criticamente diferentes linguagens em contextos sociais.', 'Linguagens', 'Ensino Médio'),
    ('EM13LGG202', 'Compreender processos de circulação e recepção de textos.', 'Linguagens', 'Ensino Médio'),
    ('EM13LGG203', 'Avaliar discursos e seus efeitos de sentido.', 'Linguagens', 'Ensino Médio'),
    ('EM13LGG204', 'Produzir textos argumentativos em diferentes mídias.', 'Linguagens', 'Ensino Médio'),
    ('EM13LGG205', 'Interpretar textos multimodais de maior complexidade.', 'Linguagens', 'Ensino Médio'),
    ('EM13LGG206', 'Utilizar recursos linguísticos de forma estratégica.', 'Linguagens', 'Ensino Médio'),
    ('EM13LGG301', 'Analisar criticamente discursos em diferentes linguagens e mídias.', 'Linguagens', 'Ensino Médio'),
    ('EM13LGG302', 'Avaliar estratégias argumentativas em textos.', 'Linguagens', 'Ensino Médio'),
    ('EM13LGG303', 'Produzir textos argumentativos com consistência e autoria.', 'Linguagens', 'Ensino Médio'),
    ('EM13LGG304', 'Interpretar textos multimodais complexos.', 'Linguagens', 'Ensino Médio'),
    ('EM13LGG305', 'Utilizar recursos linguísticos de forma estratégica e crítica.', 'Linguagens', 'Ensino Médio'),
    ('EM13LGG306', 'Analisar práticas de linguagem em contextos sociais diversos.', 'Linguagens', 'Ensino Médio'),
    ('EM13MAT101', 'Resolver problemas envolvendo números reais.', 'Matemática', 'Ensino Médio'),
    ('EM13MAT102', 'Compreender funções e suas representações.', 'Matemática', 'Ensino Médio'),
    ('EM13MAT103', 'Analisar gráficos e tabelas.', 'Matemática', 'Ensino Médio'),
    ('EM13MAT104', 'Resolver problemas envolvendo proporcionalidade.', 'Matemática', 'Ensino Médio'),
    ('EM13MAT105', 'Aplicar conceitos algébricos em situações-problema.', 'Matemática', 'Ensino Médio'),
    ('EM13MAT106', 'Interpretar dados estatísticos.', 'Matemática', 'Ensino Médio'),
    ('EM13MAT201', 'Resolver problemas envolvendo funções.', 'Matemática', 'Ensino Médio'),
    ('EM13MAT202', 'Analisar gráficos e representações matemáticas.', 'Matemática', 'Ensino Médio'),
    ('EM13MAT203', 'Aplicar conceitos de geometria em situações-problema.', 'Matemática', 'Ensino Médio'),
    ('EM13MAT204', 'Resolver problemas envolvendo probabilidade.', 'Matemática', 'Ensino Médio'),
    ('EM13MAT205', 'Interpretar dados estatísticos.', 'Matemática', 'Ensino Médio'),
    ('EM13MAT206', 'Modelar situações reais com matemática.', 'Matemática', 'Ensino Médio'),
    ('EM13MAT301', 'Resolver problemas complexos envolvendo funções.', 'Matemática', 'Ensino Médio'),
    ('EM13MAT302', 'Analisar e interpretar gráficos e modelos matemáticos.', 'Matemática', 'Ensino Médio'),
    ('EM13MAT303', 'Aplicar conceitos de geometria analítica.', 'Matemática', 'Ensino Médio'),
    ('EM13MAT304', 'Resolver problemas envolvendo probabilidade e estatística.', 'Matemática', 'Ensino Médio'),
    ('EM13MAT305', 'Modelar situações reais com ferramentas matemáticas.', 'Matemática', 'Ensino Médio'),
    ('EM13MAT306', 'Avaliar resultados e estratégias matemáticas.', 'Matemática', 'Ensino Médio')
ON CONFLICT (code) DO NOTHING;